### ISSUE TITLE
Race condition on send/join.

### ISSUE THREAD

**Issue by cmeiklejohn** [lasp-lang/partisan#112]
There's a race condition on join's and sends.

If a node calls join, and immediately attempts to send a message on that channel, the node might try to send before the connection is established with the default backend.  This is because joining is async: the join returns OK immediately, but sending is unavailable until the connection is established, which is a callback into the peer service manager once the connection is open. 

This is akin to nosuspend in erlang:send, but not the default behavior of partisan.  

Two options exist for handling this:

* Either buffer messages until the connection is open; however, the question remains on how we handle this buffer and ensure it doesn't grow indefinitely; or
* Provide a sync_join option that can be used, where the join is a call and blocks until the join has been successfully processed.

This was discovered during adapting Riak Core to use partisan, which attempts to send immediately after a join, because a join is blocking to ensure the disterl connection has been established.

Thoughts?  @tsloughter @seancribbs @slfritchie

**Comment by seancribbs** [comment]
You could prevent buffer overload by suspending processes that send messages to the unopened connection, then resuming them when the connection is established or their message has been sent.

**Comment by cmeiklejohn** [comment]
Opened #115 to address.
