### ISSUE TITLE
Jitter on connect.

### ISSUE THREAD

**Issue by cmeiklejohn** [lasp-lang/partisan#114]
In the default manager, when a cluster of nodes learns about a new node in the cluster, they all try to connect to it immediately, which because of the listen queue, can lead to timeouts, causing the cluster to fail to connect to peers.

One option here is to use a jitter parameter, which would prevent nodes from connecting immediately to a new node they just learn about.  In the case of parallelism 5, with 4 channels, this prevents 20 inbound connections from every node in the cluster hitting a new node at the exact same time.

**Comment by cmeiklejohn** [comment]
I've confirmed that jittering the connections prevents timeout issues on join, which were being seen in at least two environments running the new partisan-enabled Riak Core.  However, this solution is only probabilistic, so I welcome other solutions.

Thoughts? @slfritchie @seancribbs @tsloughter

**Comment by seancribbs** [comment]
Probabilistic is probably fine. You might also want nodes to have a random jitter when retrying after timeouts, assuming you have a multiplicative backoff scheme.

**Comment by cmeiklejohn** [comment]
Addressed in #115.
