### ISSUE TITLE
Unexpected cluster member after calling leave

### ISSUE THREAD

**Issue by xinhaoyuan** [lasp-lang/partisan#191]
Hi,

When a node (say A) calls `partisan_peer_service:leave(node())` to quit the cluster, previous gossip messages (containing A) from the cluster could reach after the restart of `partisan_default_peer_service_manager` server, and make A join the cluster unexpectedly.

Please see https://github.com/xinhaoyuan/morpheus-app-test/tree/master/partisan_test_repro_1 for demonstration.

**Comment by cmeiklejohn** [comment]
Have you tried the rename-backend branch?  That's targeted for the next release and contains a bug fix for this.  (Keep in mind, the API has been changed.)

**Comment by cmeiklejohn** [comment]
If you look at that branch at the leave test, I think that covers what you are referring to also.

**Comment by aramallo** [comment]
This is solved in v5.0.0-beta (and was potentially solved in v4 too as Chris mentions) so closing it.
