### ISSUE TITLE
epmd module

### ISSUE THREAD

**Issue by tsloughter** [lasp-lang/partisan#195]
I had a thought today after playing with [epmdless](https://github.com/oltarasenko/epmdless) again. Since partisan already keeps track of host and port, pretty much the main functionality of epmd, it might not be out of scope to include the ability to replace epmd when using partisan.

What do you think?

**Comment by cmeiklejohn** [comment]
I don't really know anything about ```epmdless```, but I'm open to suggestions.

**Comment by tsloughter** [comment]
Cool. I'll try taking a closer look at what this would look like this weekend and get back to you with suggestions.

**Comment by aramallo** [comment]
With Erlang 24 and v5.0.0-beta this can be done by simply using the new vm.args options to disable epmd and disable disterl altogether.
