### ISSUE TITLE
build with OTP 22 fail

### ISSUE THREAD

**Issue by benoitc** [lasp-lang/partisan#218]
I get the following error while building latest master with OTP 22: 

```
===> Compiling _build/default/lib/partisan/src/partisan_gen_server.erl failed
_build/default/lib/partisan/src/partisan_gen_server.erl:937: sys:get_debug/3: Deprecated function. Incorrectly documented and in fact only for internal use. Can often be replaced with sys:get_log/1.
```

**Comment by cmeiklejohn** [comment]
I haven't even tried to compile with OTP 22 yet, I assume lots of things don't work.  I'm only testing for 19.3 and 20, currently.

**Comment by benoitc** [comment]
@cmeiklejohn as far as i went in the sources it seems the only problem right now is this one and the use of a custom gen_fsm. Is there any reason to not bump to 22 or 21? I'm not even sure 19.x is a supported OTP platform now.

**Comment by cmeiklejohn** [comment]
That custom gen_server and gen_fsm are used to automatically port gen_servers and gen_fsm's to run on Partisan -- otherwise, there's no way to make them port transparently with the use of gen_server:cast.  If we want to move forward to OTP 22, then I want a compatible version of a gen_fsm/gen_server that works with that.

**Comment by benoitc** [comment]
@cmeiklejohn I saw that, was thinking that could be done using a parse transform but i can for sure portthe gen part. let me take care of it. One question is do you still want to keep gen_fsm since it has been deprecated to gen_statem?

**Comment by cmeiklejohn** [comment]
Yes, I want to keep gen_fsm, because even though it's been deprecated, many applications -- like Riak and more -- still are using a vendored version of it.

**Comment by cmeiklejohn** [comment]
I don't see how it can be a parse_transform, since the actual implementation of gen.erl is completely different when it sends messages.

**Comment by cmeiklejohn** [comment]
Maybe we can just patch around the error that's preventing the compilation in the local copy?

**Comment by benoitc** [comment]
@cmeiklejohn yes, i can have  look in 2-3 hours and send you a pr. i will look at other changes :)

**Comment by cmeiklejohn** [comment]
ok, thanks.  once we do this we probably need to update the travis config to build the proper OTP versions.

**Comment by cmeiklejohn** [comment]
thanks

**Comment by tsloughter** [comment]
This is handled so I'm closing the issue.
