### ISSUE TITLE
rebar_erl_vsn is unmaintained

### ISSUE THREAD

**Issue by benoitc** [lasp-lang/partisan#220]
Is there any reason to use `rebar_erl_vsn` ? it has not been updated on hex since June 2018 and trigger such warning:

```
===> The erlang version 22.0 is newer then the latest version known to rebar_erl_vsn (21). Features introduced between after 21 will not have flags.
```

**Comment by tsloughter** [comment]
It can probably be removed and replaced pretty easily in partisan.

**Comment by benoitc** [comment]
hrm i will check how it's used then

**Comment by tsloughter** [comment]
It has been removed.
