### ISSUE TITLE
partisan.cloud down

### ISSUE THREAD

**Issue by beardedeagle** [lasp-lang/partisan#233]
partisan.cloud appears to have expired and the site is no longer up. are there plans to restore it?

```
Registrar URL: whois.enom.com
Updated Date: 2021-01-15T10:20:31Z
Creation Date: 2019-01-14T22:50:35Z
Registry Expiry Date: 2021-01-14T22:50:35Z
```

**Comment by cmeiklejohn** [comment]
I know, I just haven't got the money to renew it yet.  (I'm a grad student.)

**Comment by sascha-wolf** [comment]
@cmeiklejohn what's the cost? Maybe this is something where the community can chip in, for example via GitHub Sponsors? I'd be happy to do so. 🙂

**Comment by beardedeagle** [comment]
@cmeiklejohn & @sascha-wolf I'm watching it as it goes through the domain expiry process. Hopefully no one is squatting on it with a backorder, or it doesn't get picked up in auction, but I or others could do the same. I don't remember the timelines for the expiry process for the .cloud gTLD, but I'll ask my coworkers.

**Comment by l2dy** [comment]
The domain has been squatted, please remove references to avoid confusion.

**Comment by beardedeagle** [comment]
@cmeiklejohn I picked up `partisan.dev` to replace `partisan.cloud`. I'll throw an SSL on it as well, let me know when and where you want it pointed at. I'll transfer it to you as well if need be, no skin off my back.

**Comment by cmeiklejohn** [comment]
That was too kind of you!!!  Thank you.  Can you point it using an ALIAS to my GitHub?

**Comment by beardedeagle** [comment]
Sorry, I've been incredibly busy. I'll get back to you as soon as this is done.
