### ISSUE TITLE
How to use Partisan ?

### ISSUE THREAD

**Issue by sleipnir** [lasp-lang/partisan#236]
Hello, how are you here?

Is there an example of an application written in Elixir using Partisan? How can I be able to upload a cluster of Elixir applications using Partisan?

**Comment by sleipnir** [comment]
Ping

**Comment by sleipnir** [comment]
> I have never personally used Partisan with Elixir but I know others have, but I'd imagine you can just use the interop between Elixir and Erlang and use it the same way you would use it with Erlang.

Thanks for the answer. And where do I find an example in Erlang?

**Comment by cmeiklejohn** [comment]
@aramallo, any thoughts here on current usage?

**Comment by aramallo** [comment]
Hi @sleipnir we are using Partisan in both OSS and proprietary SW, all in Erlang so far. You can check Bondy (https://github.com/Leapsight/bondy) our L7 service and event mesh. It uses partisan for clustering. Internally that uses another project    PlumDB (https://gitlab.com/leapsight/plum_db ) a database that uses Partisan for clustering. They are not “getting started” examples and might be difficult to read at first.  I can put together a mini example in Erlang if you want

**Comment by aramallo** [comment]
BTW I added exdoc to Partisan (in my fork which we will be integrating soon) and I will be working on adding docs and tutorials soon

**Comment by sleipnir** [comment]
> Hi @sleipnir we are using Partisan in both OSS and proprietary SW, all in Erlang so far. You can check Bondy (https://github.com/Leapsight/bondy) our L7 service and event mesh. It uses partisan for clustering. Internally that uses another project PlumDB (https://gitlab.com/leapsight/plum_db ) a database that uses Partisan for clustering. They are not “getting started” examples and might be difficult to read at first. I can put together a mini example in Erlang if you want

Thanks for replying, I'll check out the links I envy and see if I can extract something from there, thanks

**Comment by aramallo** [comment]
@sleipnir Still a draft but I started to work on a Cheatsheet Partisan. You will find it in Hex.pm docs at https://hexdocs.pm/partisan/5.0.0-beta.14/cheatsheet.html. I will keep this issue open till I have enough content there :-)

**Comment by sleipnir** [comment]
> @sleipnir Still a draft but I started to work on a Cheatsheet Partisan. You will find it in Hex.pm docs at https://hexdocs.pm/partisan/5.0.0-beta.14/cheatsheet.html. I will keep this issue open till I have enough content there :-)

Awesome. Thank you for answering. Great work!
