### ISSUE TITLE
Provide a security solution (SSL/TLS) for connections

### ISSUE THREAD

**Issue by cmeiklejohn** [lasp-lang/partisan#39]
Look into handling the upgrade of gen_tcp connections to handle SSL/TLS.

**Comment by zeeshanlakhani** [comment]
@seancribbs is currently looking into this, and we've had a brief discussion about this with regards to the move from ranch to acceptor_pool (via @tsloughter's PR) as well.

**Comment by cmeiklejohn** [comment]
Please keep us posted, because we are extremely interested in a security solution given that many folks don't want to adopt EPMD based solutions because they are too difficult to secure.

**Comment by tsloughter** [comment]
@zeeshanlakhani where is this discussion? :)

**Comment by zeeshanlakhani** [comment]
@tsloughter was just a quick, minor one :), haha.
