### ISSUE TITLE
Undefined partisan_peer_service:forward_message/3

### ISSUE THREAD

**Issue by kzemek** [lasp-lang/partisan#56]
I can't find a branch of partisan that has `forward_message/3` defined in `partisan_peer_service` module as documented in https://lasp-lang.readme.io/docs/messaging-api . The docs are also linked to from a [recent issue in lasp_pg](https://github.com/lasp-lang/lasp_pg/issues/12) which suggests they are up to date.

Are we supposed to directly use `forward_message/3` implemented in concrete manager modules instead?

**Comment by lrascao** [comment]
this can be closed via #70
