### ISSUE TITLE
Hyparview full connectivity is sometimes not being achieved

### ISSUE THREAD

**Issue by lrascao** [lasp-lang/partisan#75]
So i have a configuration of a 9 node cluster (that i start as a `rebar3 shell`) using hyparview with a max active size of 3, i then issue a join operation on all nodes at once joining through the same contact node. On some runs (not all) i end up with an "island" of 3 nodes isolated from the rest, any obvious thing that i might be missing before digging into it?

**Comment by cmeiklejohn** [comment]
How fast are you joining the nodes?

**Comment by lrascao** [comment]
Pretty fast, all of them join through the contact node at the same time.
I've re-read the paper again, how is the connectivity property ensured throughout the execution? From my limited perspective the problem seems to be that we're dropping random nodes from the active view and not making sure that the ones left are being left isolated

**Comment by cmeiklejohn** [comment]
The connectivity property is not ensured: the protocol specifically states that it's probabilistic and under certain levels of churn will not guarantee a single connected component.

Two possible solutions to reduce the effect of this:

* Have nodes reconnect when they detect they are isolated; this is specifically what we do in Lasp;
* Have nodes round-robin on join, to ensure that a single nodes active view doesn't get cycled through by the joins in quick succession.

**Comment by lrascao** [comment]
I see, i'll check out Lasp's approach then

**Comment by cmeiklejohn** [comment]
We're open to other suggestions, but, that's the best that we've come up with so far.
