### ISSUE TITLE
Confusing results from the new multi-ip join

### ISSUE THREAD

**Issue by tsloughter** [lasp-lang/partisan#89]
I'm seeing a weird result from upgrading to the current master of partisan using the default peer service manager.

We use DNS to discover the hosts we want to connect to, including their hostnames, ips and ports:

```
N = #{name => Node,
      listen_addrs => [#{ip => IP, port => PartisanPort}],
      parallelism => 1},
partisan_peer_service:join(N)
```

In the logs though I continue to see the error:

```
{unexpected_peer, <node()>, #{listen_addrs => [#{ip => {0,0,0,0}, port => 10200}]}, name => Node, ...}
```

Those are the defaults that I set through `$IP` and `$PEER_PORT` but are never the values sent with the `join` that gets called above.

I have been unable to track down where it could possibly be ending up deciding it wants to connect to `{0,0,0,0}`.

My guess was that the node is using defaults when it is connected to from another and tries to initiate. So node-2 connects to node-1 and now node-1 tries to connect to node-2 on `{0,0,0,0}` even though it was already connecting to node-2 on the IP it got from the DNS query.

But I can't find where that would be happening if it were the case.

**Comment by cmeiklejohn** [comment]
Hrm, ```$IP```?  Shouldn't you be using ```$PEER_IP```?

**Comment by tsloughter** [comment]
It uses `$IP` in `partisan_config`.

**Comment by cmeiklejohn** [comment]
Ah, right.  In your log, there should be a "Peer ~p isn't ~p." message around where you're seeing the unexpected peer messages.  Can you find that line and throw it in this issue?

**Comment by tsloughter** [comment]
Yea. And note that this is a log from the node `vonnegut@nucleus-02-chain1-0:
```
Peer 'vonnegut@nucleus-02-chain1-0.nucleus-02-vonnegut.default.svc.cluster.local' isn't #{listen_addrs => [#{ip => {0,0,0,0},port => 10200}],
name => 'vonnegut@nucleus-02-chain1-1.nucleus-02-vonnegut.default.svc.cluster.local',parallelism => 1}.
```

**Comment by tsloughter** [comment]
Issue related to state merging. I fixed it for my case by setting `$IP` to the actual ip address instead of `0.0.0.0`.
